/* eslint-env node */
/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                // Map semantic tokens to Tailwind classes
                bg: {
                    primary: "var(--color-bg-primary)",
                    secondary: "var(--color-bg-secondary)",
                    tertiary: "var(--color-bg-tertiary)",
                    overlay: "var(--color-bg-overlay)",
                },
                fg: {
                    primary: "var(--color-text-primary)",
                    secondary: "var(--color-text-secondary)",
                    tertiary: "var(--color-text-tertiary)",
                    inverse: "var(--color-text-inverse)",
                    disabled: "var(--color-text-disabled)",
                },
                border: {
                    DEFAULT: "var(--color-border-default)",
                    muted: "var(--color-border-muted)",
                    focus: "var(--color-border-focus)",
                },
                primary: {
                    50: "var(--color-primary-50)",
                    100: "var(--color-primary-100)",
                    200: "var(--color-primary-200)",
                    300: "var(--color-primary-300)",
                    400: "var(--color-primary-400)",
                    500: "var(--color-primary-500)",
                    600: "var(--color-primary-600)",
                    700: "var(--color-primary-700)",
                    800: "var(--color-primary-800)",
                    900: "var(--color-primary-900)",
                },
                success: {
                    50: "var(--color-success-50)",
                    100: "var(--color-success-100)",
                    200: "var(--color-success-200)",
                    300: "var(--color-success-300)",
                    400: "var(--color-success-400)",
                    500: "var(--color-success-500)",
                    600: "var(--color-success-600)",
                    700: "var(--color-success-700)",
                    800: "var(--color-success-800)",
                    900: "var(--color-success-900)",
                },
                warning: {
                    50: "var(--color-warning-50)",
                    100: "var(--color-warning-100)",
                    200: "var(--color-warning-200)",
                    300: "var(--color-warning-300)",
                    400: "var(--color-warning-400)",
                    500: "var(--color-warning-500)",
                    600: "var(--color-warning-600)",
                    700: "var(--color-warning-700)",
                    800: "var(--color-warning-800)",
                    900: "var(--color-warning-900)",
                },
                danger: {
                    50: "var(--color-danger-50)",
                    100: "var(--color-danger-100)",
                    200: "var(--color-danger-200)",
                    300: "var(--color-danger-300)",
                    400: "var(--color-danger-400)",
                    500: "var(--color-danger-500)",
                    600: "var(--color-danger-600)",
                    700: "var(--color-danger-700)",
                    800: "var(--color-danger-800)",
                    900: "var(--color-danger-900)",
                },
                // Component backgrounds
                input: "var(--input-bg)",
                dialog: "var(--dialog-bg)",
                card: "var(--card-bg)",
            },
            spacing: {
                0: "var(--space-0)",
                1: "var(--space-1)",
                2: "var(--space-2)",
                3: "var(--space-3)",
                4: "var(--space-4)",
                5: "var(--space-5)",
                6: "var(--space-6)",
                8: "var(--space-8)",
                10: "var(--space-10)",
                12: "var(--space-12)",
                16: "var(--space-16)",
            },
            borderRadius: {
                none: "var(--radius-none)",
                sm: "var(--radius-sm)",
                DEFAULT: "var(--radius-md)",
                md: "var(--radius-md)",
                lg: "var(--radius-lg)",
                xl: "var(--radius-xl)",
                "2xl": "var(--radius-2xl)",
                full: "var(--radius-full)",
            },
            fontFamily: {
                sans: "var(--font-sans)",
                mono: "var(--font-mono)",
            },
            fontSize: {
                xs: "var(--text-xs)",
                sm: "var(--text-sm)",
                base: "var(--text-base)",
                lg: "var(--text-lg)",
                xl: "var(--text-xl)",
                "2xl": "var(--text-2xl)",
                "3xl": "var(--text-3xl)",
            },
            lineHeight: {
                tight: "var(--leading-tight)",
                normal: "var(--leading-normal)",
                relaxed: "var(--leading-relaxed)",
            },
            fontWeight: {
                normal: "var(--weight-normal)",
                medium: "var(--weight-medium)",
                semibold: "var(--weight-semibold)",
                bold: "var(--weight-bold)",
            },
            boxShadow: {
                sm: "var(--shadow-sm)",
                DEFAULT: "var(--shadow-md)",
                md: "var(--shadow-md)",
                lg: "var(--shadow-lg)",
                xl: "var(--shadow-xl)",
                "2xl": "var(--shadow-2xl)",
            },
            zIndex: {
                dropdown: "var(--z-dropdown)",
                sticky: "var(--z-sticky)",
                fixed: "var(--z-fixed)",
                backdrop: "var(--z-backdrop)",
                modal: "var(--z-modal)",
                popover: "var(--z-popover)",
                tooltip: "var(--z-tooltip)",
                toast: "var(--z-toast)",
            },
            transitionDuration: {
                fast: "var(--duration-fast)",
                normal: "var(--duration-normal)",
                slow: "var(--duration-slow)",
                slower: "var(--duration-slower)",
            },
            transitionTimingFunction: {
                "ease-in": "var(--ease-in)",
                "ease-out": "var(--ease-out)",
                "ease-in-out": "var(--ease-in-out)",
            },
        },
    },
    plugins: [],
};
